# Deterministic synthetic images for the generated cases of recipe `qwen3-vl-reranker-2b`.
#
# No media in these cases comes from a third-party source: the model card's own example image
# (the URL in card-*.yaml source.quote) carries no licence that allows redistribution in an
# Apache-2.0 repository, so every media file here is generated by this script. Content is
# seeded geometric gradients -- the cases exercise the media path, not image aesthetics, and
# the generated cases' scores are filled by the GPU wave (expected.values: null).
#
# Every image is 1280x1024 px = 1310720 px^2 = the recipe's max_pixels (serve.mm_processor_kwargs)
# exactly, so the engine expands each one to 1280 image tokens (px/1024 after the 2x2 merge,
# recipe R20); both dimensions are multiples of the 32-px resize factor, so smart_resize leaves
# them untouched and the repo's min_pixels default (4095 vs the recipe's 4096) cannot matter.
#
# Regenerate (writes byte-identical files for a given Pillow version): python make_media.py

from __future__ import annotations

from pathlib import Path

import numpy as np
from PIL import Image

SIZE = (1280, 1024)  # (width, height) px = max_pixels exactly -> 1280 image tokens

FILES = {
    "gen-image-short-a": ("lighthouse", 11),
    "gen-image-uniform-a": ("lighthouse", 21),
    "gen-image-uniform-b": ("lighthouse", 22),
    "gen-image-uniform-c": ("lighthouse", 23),
    "gen-mixed-modality-a": ("glacier", 31),
    "gen-mixed-modality-b": ("glacier", 32),
    "gen-image-long-over-a": ("maintenance", 41),
}


def draw(theme: str, seed: int) -> Image.Image:
    """One seeded image: vertical gradient in the theme's palette plus seeded rectangles."""
    palettes = {
        "lighthouse": [(16, 42, 66), (222, 138, 57)],  # dusk sky to beacon warm
        "glacier": [(214, 233, 244), (43, 84, 110)],  # ice to deep crevasse blue
        "maintenance": [(38, 44, 48), (196, 178, 128)],  # metal grey to lamp brass
    }
    top, bottom = palettes[theme]
    h, w = SIZE[1], SIZE[0]
    rows = np.linspace(0.0, 1.0, h, dtype=np.float32)[:, None]
    base = (1.0 - rows) * np.array(top, dtype=np.float32) + rows * np.array(bottom, dtype=np.float32)
    img = np.repeat(base[:, None, :], w, axis=1)
    nrng = np.random.default_rng(seed)
    for _ in range(12):  # seeded rectangles: the image "content"
        x0, y0 = int(nrng.integers(0, w - 160)), int(nrng.integers(0, h - 160))
        bw, bh = int(nrng.integers(40, 320)), int(nrng.integers(40, 320))
        shade = float(nrng.uniform(0.55, 1.45))
        img[y0 : y0 + bh, x0 : x0 + bw, :] = np.clip(img[y0, x0] * shade, 0, 255)
    return Image.fromarray(img.astype(np.uint8), mode="RGB")


def main() -> None:
    out = Path(__file__).parent
    for name, (theme, seed) in FILES.items():
        path = out / f"{name}.png"
        draw(theme, seed).save(path, format="PNG")
        print(f"wrote {path.name}")


if __name__ == "__main__":
    main()
