"""The exported JSON Schemas: configs, artifacts and command outputs.

Every schema has a name (``run-manifest``), a version (``v1``) and an id, ``rcp-ndcg.<name>.v1``. Artifacts
(manifests, reports, judgements) and the data of every ``--json`` command repeat the id in their ``schema`` field;
configs (``run-config``, ``judge-config``) do not, as a config file refuses keys its model lacks, and neither does
the command tree. The exported document carries

* ``"$id"``: :data:`SCHEMA_ID_BASE` ``/<name>.v1.json``, an identifier that names the committed copy in the
  repository's ``schemas/`` directory (regenerated by ``rcp-ndcg schema export --out schemas``); it is not a URL
  to fetch the schema from (``rcp-ndcg schema show <name>`` prints it), and
* ``"x-rcp-ndcg-schema": "rcp-ndcg.<name>.v1"``.

The output schema of every ``--json`` command is exported under the name its command declares; the other
entries are listed in :data:`SCHEMAS`. A consumer can validate before parsing and generate its own types instead
of inferring the shape from one example file.

Every property carries a ``description``: the field's own, else the entry for it in its model's ``Attributes:``
section (which then leaves the model's description). Cross-reference markup is reduced to plain names.
"""

from __future__ import annotations

import importlib
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal

from rcp_ndcg.errors import UsageError

SCHEMA_ID_BASE = "https://github.com/cohere-ai/rcp-ndcg/blob/main/schemas"
JSON_SCHEMA_DIALECT = "https://json-schema.org/draft/2020-12/schema"
VERSION = "v1"

SchemaKind = Literal["config", "artifact", "cli-output"]


@dataclass(frozen=True)
class SchemaEntry:
    """One exported schema: its kind and the pydantic model (``"module:Class"``) it is generated from.

    ``tagged`` entries describe payloads that carry their schema id in a ``schema`` field the model itself does
    not declare (a command's ``--json`` data); the exported schema then requires that field.
    """

    name: str
    kind: SchemaKind
    model: str
    tagged: bool = False

    @property
    def schema_id(self) -> str:
        """``rcp-ndcg.<name>.v1``: the value payloads carry in their ``schema`` field."""
        return f"rcp-ndcg.{self.name}.{VERSION}"

    @property
    def url(self) -> str:
        """The ``$id``: where the committed copy lives in the repository."""
        return f"{SCHEMA_ID_BASE}/{self.name}.{VERSION}.json"


#: The schemas that are not the output of a ``--json`` command.
SCHEMAS: tuple[SchemaEntry, ...] = (
    SchemaEntry("run-config", "config", "rcp_ndcg.runs.config:RunConfig"),
    SchemaEntry("run-manifest", "artifact", "rcp_ndcg.runs.manifest:RunManifest"),
    SchemaEntry("eval-report", "artifact", "rcp_ndcg.eval:EvalReport"),
    SchemaEntry("comparison", "artifact", "rcp_ndcg.eval:Comparison"),
    SchemaEntry("result-record", "artifact", "rcp_ndcg.results:ResultRecord"),
    SchemaEntry("judge-config", "config", "rcp_ndcg.judging.client:JudgeConfig"),
    SchemaEntry("judgement", "artifact", "rcp_ndcg_core.schemas:Judgement"),
    SchemaEntry("judgement-store", "artifact", "rcp_ndcg.judging.store:StoreIdentity"),
    SchemaEntry("calibration", "artifact", "rcp_ndcg.calibration.fit:CalibrationItems"),
    SchemaEntry("calibration-coverage", "artifact", "rcp_ndcg.calibration.coverage:CalibrationCoverage"),
    SchemaEntry("calibration-identity", "artifact", "rcp_ndcg.calibration.fit:CalibrationIdentity"),
    SchemaEntry("extension-record", "artifact", "rcp_ndcg.calibration.extend:ExtensionRecord"),
    SchemaEntry("index", "artifact", "rcp_ndcg.retrieval._api:Index"),
    SchemaEntry("cost-estimate", "cli-output", "rcp_ndcg.judging.cost:CostEstimate"),
    SchemaEntry("extension", "cli-output", "rcp_ndcg.calibration.extend:Extension"),
    SchemaEntry("cli", "cli-output", "rcp_ndcg.cli.output:CliEnvelope"),
    SchemaEntry("commands", "cli-output", "rcp_ndcg.cli.introspect:CommandTree"),
    SchemaEntry("command-index", "cli-output", "rcp_ndcg.cli.introspect:CommandIndex"),
)


def _entries() -> dict[str, SchemaEntry]:
    """Every exported schema by name: :data:`SCHEMAS` plus the output model of every declared command."""
    from rcp_ndcg.cli.introspect import command_specs

    entries = {entry.name: entry for entry in SCHEMAS}
    for spec in command_specs().values():
        if spec.result is None:
            continue
        name = spec.output_schema.removeprefix("rcp-ndcg.").removesuffix(f".{VERSION}")
        known = entries.get(name)
        if known is not None and _model(known) is not spec.result:
            raise RuntimeError(f"schema {name!r} is declared by two models: {known.model} and {spec.result}")
        model = f"{spec.result.__module__}:{spec.result.__qualname__}"
        entries.setdefault(name, SchemaEntry(name, "cli-output", model, tagged=True))
    return dict(sorted(entries.items()))


def _model(entry: SchemaEntry) -> Any:
    module_path, attribute = entry.model.split(":")
    return getattr(importlib.import_module(module_path), attribute)


def names() -> list[str]:
    """The names of every exported schema, sorted."""
    return list(_entries())


def entries() -> list[SchemaEntry]:
    """Every exported schema, sorted by name."""
    return list(_entries().values())


def show(name: str) -> dict[str, Any]:
    """The JSON Schema called *name*.

    Args:
        name: A schema name (``run-manifest``) or id (``rcp-ndcg.run-manifest.v1``).

    Raises:
        UsageError: No schema has that name; the details list the known names.
    """
    key = name.removeprefix("rcp-ndcg.").removesuffix(f".{VERSION}")
    entry = _entries().get(key)
    if entry is None:
        known = names()
        raise UsageError(f"unknown schema {name!r}", hint=f"known: {', '.join(known)}", details={"known": known})
    model = _model(entry)
    body = _described(model.model_json_schema(mode="serialization"), _models(model))
    if entry.tagged and "schema" not in body.get("properties", {}):
        body["properties"] = {"schema": {"const": entry.schema_id, "type": "string"}, **body.get("properties", {})}
        body["required"] = ["schema", *body.get("required", [])]
    return {
        "$schema": JSON_SCHEMA_DIALECT,
        "$id": entry.url,
        "x-rcp-ndcg-schema": entry.schema_id,
        **{key: value for key, value in body.items() if key not in ("$schema", "$id")},
    }


_ROLE = re.compile(r":(?:func|class|meth|attr|data|mod|exc|obj|ref):`(~?)([^`<]*?)(?:\s*<[^>]*>)?`")
_ATTRIBUTE = re.compile(r"^(\w+)(?: \([^)]*\))?:\s*(.*)$")


def _plain(text: str) -> str:
    """Docstring markup as plain text: ``:role:`~a.b.c``` -> ``c``, ``:role:`a.b``` -> ``a.b``."""
    return _ROLE.sub(lambda m: m.group(2).rsplit(".", 1)[-1] if m.group(1) else m.group(2), text)


def _attributes(description: str) -> tuple[str, dict[str, str]]:
    """A model description split into its prose and its ``Attributes:`` entries (Google style)."""
    lines = description.splitlines()
    start = next((i for i, line in enumerate(lines) if line.strip() == "Attributes:"), None)
    if start is None:
        return description, {}
    base = len(lines[start]) - len(lines[start].lstrip())
    entries: dict[str, list[str]] = {}
    current: list[str] | None = None
    end = len(lines)
    for index in range(start + 1, len(lines)):
        line = lines[index]
        indent = len(line) - len(line.lstrip())
        if line.strip() and indent <= base:
            end = index
            break
        match = _ATTRIBUTE.match(line.strip())
        if match and indent <= base + 4:
            current = entries.setdefault(match.group(1), [])
            current.append(match.group(2))
        elif current is not None and line.strip():
            current.append(line.strip())
    prose = "\n".join(lines[:start] + lines[end:]).strip()
    return prose, {name: " ".join(parts).strip() for name, parts in entries.items()}


def _models(model: Any) -> dict[str, Any]:
    """``{class name: class}`` of every model reachable from ``model``'s fields (the schema's ``$defs`` names)."""
    import typing

    from pydantic import BaseModel

    out: dict[str, Any] = {}
    pending = [model]
    while pending:
        cls = pending.pop()
        if not (isinstance(cls, type) and issubclass(cls, BaseModel)) or cls.__name__ in out:
            continue
        out[cls.__name__] = cls
        stack = [info.annotation for info in cls.model_fields.values()]
        while stack:
            annotation = stack.pop()
            if isinstance(annotation, type) and issubclass(annotation, BaseModel):
                pending.append(annotation)
            stack.extend(typing.get_args(annotation))
    return out


def _field_docs(cls: Any) -> dict[str, str]:
    """``{property name: text}`` from the ``Attributes:`` sections of ``cls`` and its bases (the nearest wins)."""
    import inspect

    docs: dict[str, str] = {}
    for base in reversed(cls.__mro__):
        if base.__dict__.get("__doc__"):
            docs.update(_attributes(inspect.cleandoc(base.__doc__))[1])
    names = {name: info.serialization_alias or info.alias or name for name, info in cls.model_fields.items()}
    return {names.get(name, name): text for name, text in docs.items() if text}


def _described(schema: dict[str, Any], models: dict[str, Any]) -> dict[str, Any]:
    """``schema`` with each object's ``Attributes:`` entries moved onto its properties, and markup made plain."""
    nodes = [(schema.get("title", ""), schema), *schema.get("$defs", {}).items()]
    for title, node in nodes:
        properties = node.get("properties")
        if not isinstance(properties, dict):
            continue
        entries = _field_docs(models[title]) if title in models else {}
        description = node.get("description")
        if isinstance(description, str):
            prose, own = _attributes(description)
            entries = {**entries, **own}
            if own:
                node["description"] = prose
        for name, text in entries.items():
            if name in properties and not properties[name].get("description"):
                properties[name]["description"] = text
    return _plain_everywhere(schema)


def _plain_everywhere(value: Any) -> Any:
    if isinstance(value, dict):
        return {
            k: (_plain(v) if k == "description" and isinstance(v, str) else _plain_everywhere(v))
            for k, v in value.items()
        }
    if isinstance(value, list):
        return [_plain_everywhere(item) for item in value]
    return value


def export(out_dir: str | Path) -> list[Path]:
    """Write every schema as ``<out_dir>/<name>.v1.json`` (the directory is created) and return the paths."""
    target = Path(out_dir)
    target.mkdir(parents=True, exist_ok=True)
    written = []
    for name in names():
        path = target / f"{name}.{VERSION}.json"
        path.write_text(json.dumps(show(name), indent=2, sort_keys=True) + "\n", encoding="utf-8")
        written.append(path)
    return written


__all__ = [
    "JSON_SCHEMA_DIALECT",
    "SCHEMAS",
    "SCHEMA_ID_BASE",
    "VERSION",
    "SchemaEntry",
    "SchemaKind",
    "entries",
    "export",
    "names",
    "show",
]
