"""The public-name freeze: every name in the pinned Python surface is documented, or frozen deliberately.

Workstream 07 freezes the public surface once, before 0.0.1: the snapshot
(``snapshots/python_api.json``, the ``__all__`` of ``surface.PUBLIC_MODULES``) is the definition of what is
public, and every name in it is either mentioned on a page under ``docs/`` or listed in
``undocumented_public_names.json`` beside this file. The list is the advanced surface the reference pages do
not present one by one (a registry constant, an estimator class, a mechanism name); it is a reviewed diff,
not a default: a new public name fails this test until it is documented or added to the list, and a name that
gains a docs page fails until it is removed. The list may shrink freely; it grows only on purpose.
"""

from __future__ import annotations

import json
import os
import re
from pathlib import Path

import pytest

from tests.contract.surface import REPO

SNAPSHOTS = Path(__file__).parent / "snapshots"
DOCS = REPO / "docs"
FREEZE = Path(__file__).parent / "undocumented_public_names.json"
HINT = (
    "document the name on a page under docs/, or add it to tests/contract/undocumented_public_names.json "
    "(a reviewed freeze entry; the list is regenerated with `pytest tests/contract --update-snapshots`)"
)


@pytest.fixture()
def update_snapshots(request: pytest.FixtureRequest) -> bool:
    """The contract suite's own flag (defined in ``test_public_surface``): this module's freeze list is
    regenerated by the same ``--update-snapshots`` run that rewrites the snapshots."""
    return bool(request.config.getoption("--update-snapshots")) or os.environ.get("RCP_NDCG_UPDATE_SNAPSHOTS") == "1"


def public_names() -> list[str]:
    """Every name the pinned Python surface exports, across the public modules."""
    snapshot = json.loads((SNAPSHOTS / "python_api.json").read_text(encoding="utf-8"))
    return sorted({name for entry in snapshot.values() for name in entry.get("all", {})})


def undocumented(names: list[str]) -> list[str]:
    """The names no page under ``docs/`` mentions (a word match, so a ``~module.Name`` cross-reference counts)."""
    text = "\n".join(path.read_text(encoding="utf-8") for path in sorted(DOCS.rglob("*.md")))
    return [name for name in names if not re.search(rf"\b{re.escape(name)}\b", text)]


def test_every_public_name_is_documented_or_frozen(update_snapshots: bool) -> None:
    """The freeze is complete and current in both directions (see the module docstring)."""
    names = public_names()
    assert names, "the python_api snapshot pins no names; the freeze would be vacuous"
    current = undocumented(names)
    if update_snapshots:
        FREEZE.write_text(json.dumps(current, indent=2) + "\n", encoding="utf-8")
        return
    frozen = json.loads(FREEZE.read_text(encoding="utf-8"))
    added = sorted(set(current) - set(frozen))
    assert not added, f"public names on no docs page and not frozen: {added}. {HINT}"
    fixed = sorted(set(frozen) - set(current))
    assert not fixed, f"documented or removed names still frozen: {fixed}. Regenerate the freeze list ({HINT})"


def test_the_frozen_names_are_names_of_the_pinned_surface() -> None:
    """The list holds public names only: a typo or a stale name would freeze nothing."""
    frozen = json.loads(FREEZE.read_text(encoding="utf-8"))
    assert frozen, "the freeze list is empty; regenerate it if the surface really is fully documented"
    assert len(frozen) == len(set(frozen)), "the freeze list holds duplicates"
    assert set(frozen) <= set(public_names()), sorted(set(frozen) - set(public_names()))
