"""The generated API reference: one Markdown page per public module, from the pinned surface snapshot.

The public surface is pinned as data (``tests/contract/snapshots/python_api.json``: the ``__all__`` of
:data:`PUBLIC_MODULES`, each name with its kind, signature and model fields). ``rcp-ndcg docs api --out
docs/reference/api`` renders that snapshot plus the modules' own docstrings into one page per module -- every
public name with its signature and one-line role -- so the long tail of the surface is documented mechanically
while the curated pages under ``docs/`` carry the narrative. The contract suite regenerates the pages and diffs
them against the committed copies, so the docs cannot drift from the surface.
"""

from __future__ import annotations

import ast
import importlib
import inspect
import json
from collections.abc import Mapping
from pathlib import Path
from typing import Any

from rcp_ndcg.errors import UsageError

__all__ = [
    "DEFAULT_SNAPSHOT",
    "PUBLIC_MODULES",
    "page_name",
    "read_snapshot",
    "render_page",
    "render_pages",
    "write_pages",
]

#: The public Python modules: the facade, the core with its documented modules, the modules the docs present
#: as API, and ``rcp_ndcg_vllm.recipe`` -- the lean serving package's public recipe module (``Recipe``,
#: ``load_recipe``, ``iter_recipes``, the serve-argv builder). The rest of ``rcp_ndcg_vllm`` and all of
#: ``rcp_ndcg_test`` are internal. ``tests/contract`` pins this list as the surface snapshot; a name is public
#: only through the ``__all__`` of one of these modules.
PUBLIC_MODULES: tuple[str, ...] = (
    "rcp_ndcg_core",
    "rcp_ndcg_core.gain",
    "rcp_ndcg_core.irt",
    "rcp_ndcg_core.metric",
    "rcp_ndcg_core.protocol",
    "rcp_ndcg_core.records",
    "rcp_ndcg",
    "rcp_ndcg.calibration",
    "rcp_ndcg.data",
    "rcp_ndcg.data.preprocess",
    "rcp_ndcg.data.revisions",
    "rcp_ndcg.errors",
    "rcp_ndcg.eval",
    "rcp_ndcg.eval.mteb",
    "rcp_ndcg.examples",
    "rcp_ndcg.inference",
    "rcp_ndcg.judging",
    "rcp_ndcg.results",
    "rcp_ndcg.retrieval",
    "rcp_ndcg.runners",
    "rcp_ndcg.runs",
    "rcp_ndcg.testing",
    "rcp_ndcg_vllm.recipe",
)

#: The pinned surface snapshot, relative to the repository root: the definition of what is public.
DEFAULT_SNAPSHOT = Path("tests/contract/snapshots/python_api.json")

_HEADER = (
    "Every name below is pinned by `tests/contract/snapshots/python_api.json` (the `__all__` of the public\n"
    "modules); this page is generated by `rcp-ndcg docs api --out docs/reference/api` and never edited by hand.\n"
)


def page_name(module: str) -> str:
    """The page file name of *module* (``rcp_ndcg_core.metric`` -> ``rcp_ndcg_core.metric.md``)."""
    return f"{module}.md"


def read_snapshot(path: str | Path = DEFAULT_SNAPSHOT) -> dict[str, dict[str, Any]]:
    """The pinned surface snapshot: module -> ``{"all": {name: described}}``.

    Args:
        path: The snapshot file (default: :data:`DEFAULT_SNAPSHOT`, relative to the working directory).

    Returns:
        The snapshot as JSON.

    Raises:
        UsageError: The file does not exist, or does not hold the module -> entry mapping the snapshot has.
    """
    source = Path(path)
    if not source.is_file():
        raise UsageError(
            f"no surface snapshot at {source}",
            hint=f"run from the repository root, or pass --snapshot PATH (the default is {DEFAULT_SNAPSHOT})",
        )
    data = json.loads(source.read_text(encoding="utf-8"))
    if not isinstance(data, dict) or not all(isinstance(entry, dict) for entry in data.values()):
        raise UsageError(f"{source} is not a surface snapshot", hint="it maps each public module to its names")
    return data


def _first_line(text: str) -> str:
    """The first paragraph of a docstring, on one line."""
    return " ".join(text.strip().split("\n\n", 1)[0].split())


def _module(name: str) -> Any:
    """The imported module, or ``None`` when its optional extra is not installed."""
    try:
        return importlib.import_module(name)
    except ImportError:
        return None


def _constant_doc(module_name: str, name: str) -> str:
    """The one-line docstring of a module constant: the string literal after its assignment, else its comment."""
    try:
        source = inspect.getsourcefile(importlib.import_module(module_name))
    except ImportError:
        return ""
    if source is None:
        return ""
    try:
        text = Path(source).read_text(encoding="utf-8")
        tree = ast.parse(text)
    except (OSError, SyntaxError):
        return ""
    for index, node in enumerate(tree.body[:-1]):
        if not isinstance(node, ast.Assign) or not any(
            isinstance(target, ast.Name) and target.id == name for target in node.targets
        ):
            continue
        following = tree.body[index + 1]
        if (
            isinstance(following, ast.Expr)
            and isinstance(following.value, ast.Constant)
            and isinstance(following.value.value, str)
        ):
            return _first_line(following.value.value)
        return _comment_doc(text.splitlines(), node.lineno)
    return ""


def _comment_doc(lines: list[str], lineno: int) -> str:
    """The ``#:`` comment block right above line *lineno* (1-based), on one line."""
    block: list[str] = []
    index = lineno - 2
    while index >= 0 and lines[index].lstrip().startswith("#:"):
        block.insert(0, lines[index].lstrip().removeprefix("#:").strip())
        index -= 1
    return " ".join(block)


def _role(module_name: str, name: str, described: Mapping[str, Any]) -> str:
    """The one-line role of a name: its own docstring's first paragraph, else its home module's, else its comment.

    A class's own docstring is read from its ``__dict__``: an undocumented subclass would otherwise inherit its
    base's (``ID = str`` would document itself with ``str``'s), and a constant or alias carries its role as the
    string literal (or ``#:`` comment) beside its assignment, never as an instance ``__doc__``.
    """
    if described["kind"] in ("constant", "literal_alias", "type_alias"):
        return _constant_doc(module_name, name)
    for owner in (module_name, described.get("defined_in")):
        if not owner:
            continue
        module = _module(owner)
        if module is None:
            continue
        obj = getattr(module, name, None)
        doc = vars(obj).get("__doc__") if isinstance(obj, type) else getattr(obj, "__doc__", None)
        if doc:
            return _first_line(doc)
    return ""


def _literal(value: Any) -> str:
    return repr(value)


def _parameter(param: Mapping[str, Any]) -> str:
    kind, name = param["kind"], param["name"]
    if kind == "var_positional":
        return f"*{name}"
    if kind == "var_keyword":
        return f"**{name}"
    text = name
    if param["annotation"]:
        text += f": {param['annotation']}"
    if param["default"] != "<required>":
        text += f" = {_literal(param['default'])}"
    return text


def _parameters(params: list[dict[str, Any]]) -> str:
    """A parameter list from the snapshot's signature entries (the last entry is the return annotation)."""
    parts: list[str] = []
    keyword_only = any(param["kind"] == "keyword_only" for param in params[:-1])
    for index, param in enumerate(params[:-1]):
        previous = params[index - 1]["kind"] if index else None
        following = params[index + 1]["kind"] if index + 1 < len(params) - 1 else None
        if keyword_only and param["kind"] == "keyword_only" and previous != "keyword_only":
            parts.append("*")
        parts.append(_parameter(param))
        if param["kind"] == "positional_only" and following != "positional_only":
            parts.append("/")
    return f"({', '.join(parts)})"


def _fields(entry: Mapping[str, Any]) -> list[str]:
    lines = []
    for name, field in sorted(entry.get("fields", {}).items()):
        default = "" if field["required"] else f" = {_literal(field['default'])}"
        lines.append(f"- `{name}: {field['type']}`{default}")
    return lines


def _body(name: str, entry: Mapping[str, Any]) -> str:
    """The signature and structure of one name: a fenced block, plus a model's fields or an enum's values."""
    kind = entry["kind"]
    if kind == "function":
        signature = entry.get("signature")
        if isinstance(signature, list):
            returns = signature[-1].get("returns")
            arrow = f" -> {returns}" if returns else ""
            return f"```text\n{name}{_parameters(signature)}{arrow}\n```"
        return ""
    if kind in ("class", "pydantic_model", "enum", "exception", "protocol"):
        bases = ", ".join(entry.get("bases", [])) or ("BaseModel" if kind == "pydantic_model" else "")
        lines = [f"```text\nclass {name}({bases})\n```"]
        if kind == "enum":
            lines += [f"- `{value}`" for value in entry.get("values", [])]
        elif kind == "pydantic_model":
            lines += _fields(entry)
        else:
            init = entry.get("init")
            if isinstance(init, list):
                lines += [f"```text\n{name}{_parameters(init)}\n```"]
        return "\n\n".join(lines)
    if kind in ("type_alias", "literal_alias"):
        if kind == "literal_alias":
            values = " | ".join(_literal(value) for value in entry.get("values", []))
            return f"```text\n{name} = {values}\n```"
        return f"```text\n{name} = {entry.get('type', '')}\n```"
    if kind == "constant":
        value = entry.get("value", entry.get("type", ""))
        text = _literal(value)
        return f"```text\n{name} = {text if len(text) <= 200 else text[:197] + '...'}\n```"
    return ""


def render_page(module_name: str, entry: Mapping[str, Any]) -> str:
    """One module's Markdown page: the module's role, then every name with its kind, role and signature."""
    module = _module(module_name)
    doc = inspect.getdoc(module) if module is not None else None
    role = f"{_first_line(doc)}\n\n" if doc else ""
    lines = [f"# `{module_name}`", "", role + _HEADER]
    for name, described in sorted(entry.get("all", {}).items()):
        role = _role(module_name, name, described)
        lines += [f"## `{name}`", "", f"{described['kind']}" + (f" — {role}" if role else ""), ""]
        body = _body(name, described)
        if body:
            lines += [body, ""]
    return "\n".join(lines).rstrip() + "\n"


def render_pages(surface: Mapping[str, Mapping[str, Any]]) -> dict[str, str]:
    """The page of every module in *surface*, keyed by module name."""
    return {module: render_page(module, entry) for module, entry in surface.items()}


def write_pages(out: str | Path = "docs/reference/api", *, snapshot: str | Path = DEFAULT_SNAPSHOT) -> list[Path]:
    """Write one page per module of the snapshot into *out* (created), and return the paths, module-sorted.

    Args:
        out: The directory the pages are written into.
        snapshot: The pinned surface snapshot to render (default: :data:`DEFAULT_SNAPSHOT`).

    Raises:
        UsageError: The snapshot is missing or malformed (:func:`read_snapshot`).
    """
    directory = Path(out)
    directory.mkdir(parents=True, exist_ok=True)
    written = []
    for module, page in sorted(render_pages(read_snapshot(snapshot)).items()):
        path = directory / page_name(module)
        path.write_text(page, encoding="utf-8")
        written.append(path)
    return written
